apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kaiwo
    app.kubernetes.io/managed-by: kustomize
  name: webhook-service
  namespace: kaiwo-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: kaiwo-controller-manager
    app.kubernetes.io/name: kaiwo
