apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-observability

configMapGenerator:
  - name: alloy-host-config
    behavior: create
    files:
      - config.alloy
    options:
      disableNameSuffixHash: true
