apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-observability

resources:
  # Filters in execution order by ordinal
  - 100-filter-exclude-test-observability.yaml
  - 110-filter-include-test-namespace.yaml
  - 120-filter-extract-namespace-fields.yaml
  - 130-filter-classify-log-type.yaml
  - 135-filter-extract-json.yaml
  - 136-filter-parse-json-fields.yaml
  - 140-filter-parse-audit-logs.yaml
  - 150-filter-parse-event-logs.yaml
  - 160-filter-parse-pod-logs.yaml
