site_name: Kaiwo - Kubernetes AI Workload Orchestrator
theme:
  name: material
  features:
  - navigation.instant
  - navigation.instant.progress
  - navigation.tabs
  - navigation.sections
  - content.code.copy
markdown_extensions:
- def_list
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- admonition
- pymdownx.details
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
nav:
- "Home": 
  - "Overview": "index.md"
  - "Main Components": "general/main-components.md"
  - "Releases": "general/releases.md"
  - "Support": "general/support.md"
- "AI Scientist":
  - "Overview": "scientist/overview.md"
  - "Quickstart": "scientist/quickstart.md"
  - "CRDs": "scientist/crds.md"
  - "CLI": "scientist/cli.md"
  - "Scheduling": "scientist/scheduling.md"
- "Administrator":
  - "Overview": "admin/overview.md"
  - "Quickstart": "admin/quickstart.md"
  - "Installation": "admin/installation.md"
  - "Configuration": "admin/configuration.md"
  - "CRDs": "admin/crds.md"
  - "Maintenance": "admin/maintenance.md"
  - "Monitoring": "admin/monitoring.md"
  - "Authentication & Authorization": "admin/auth.md"
  - "Troubleshooting": "admin/troubleshooting.md"
- "Reference":
  - "CRD Reference": "reference/crds/kaiwo.silogen.ai.md"

